spring.application.name=libraryManagementSystem

server.port=8989

spring.datasource.url=jdbc:mysql://localhost:3306/libraryMS?createDatabaseIfNotExist=true
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
